image: python:3.9

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip
    - .venv
    # for gdal:
    - /usr/include/gdal

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:          # List of stages for jobs, and their order of execution
  - .pre
  - build
  - test
  - deploy

setting_up_env:
  stage: .pre
  tags:
    # - docker
    - linux
  # for gdal
  before_script:
    - apt update && apt install -y build-essential libgdal-dev
  script:
    - 'python --version ; pip --version'  # For debugging
    - 'pip install pip --upgrade'
    - 'pip install virtualenv'
    - 'virtualenv .venv'
    - 'source .venv/bin/activate'

build-package:
  stage: build
  tags:
    # - docker
    - linux
  # for gdal
  before_script:
    - apt update && apt install -y build-essential libgdal-dev
  script:
    - 'pip install build'  # todo fix the version!
    - "python3 -m build"
  artifacts:
    paths:
    - dist


first-test:
  stage: test    # Only starts when the job in the build stage succeedes 
  tags:
    # - docker
    - linux
  needs: ["build-package",]
  # for gdal
  before_script:
    - apt update && apt install -y build-essential libgdal-dev
  script:
    - 'source ./.venv/bin/activate'
    - 'pip install -r requirements.txt'
    - 'pip install -r tests/requirements.txt'  # this installs packages downstream as well, not ideal
    - 'pip install dist/*.whl'  # install the package
    - 'python -m pytest -vvv --cov=landiv_blur'
    - 'coverage xml'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

pages:
  stage: deploy
  tags:
    # - docker 
    - linux
  needs: 
    - "first-test"
    - "build-package"
  # for gdal
  before_script:
    - apt update && apt install -y build-essential libgdal-dev
  script:
    - 'source ./.venv/bin/activate'
    - 'pip install -r docs/requirements.txt'
    - 'sphinx-apidoc -o docs/api src/landiv_blur -f'
    - 'sphinx-build -b html docs public'
  artifacts:
    paths:
    - public
