name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        lfs: 'true'
        submodules: recursive
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -e .[testing]
    
    - name: Run tests with coverage
      run: |
        ls -ahl ./data/testing/ndvi/
        source .venv/bin/activate
        python -c "import multiprocessing; print(multiprocessing.cpu_count())"
        python -m pytest -k parallel -s -vvv --timeout 300 --junitxml=junit/test-results.xml --cov=landiv_blur
      env:
        COVERAGE_FILE: ".coverage.unittests"
    - name: Store coverage file
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-unittests
        path: .coverage.unittests
        include-hidden-files: true

  coverage:
    name: coverage-combine-publish
    runs-on: ubuntu-24.04
    needs: [unit-tests, ]
    if: |
      always()
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        id: download
        with:
          pattern: coverage-*
          merge-multiple: true
      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_COVERAGE_FILES: true

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
